services:
  # === WAREHOUSE ===
  postgres:
    container_name: warehouse
    image: postgres:15-alpine
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=en_US.utf8"
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./pipelines/data:/data:ro
      - ./pipelines/core/airflow_init.sql:/docker-entrypoint-initdb.d/airflow_init.sql:ro
      - ./pipelines/core/race_position_init.sql:/docker-entrypoint-initdb.d/race_position_init.sql:ro
      # WE ADD MORE TABLE INITS HERE
    networks:
      - data_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # === ORCHESTRATION ===
  airflow:
    container_name: airflow
    image: apache/airflow:3.0.0
    ports:
      - "8080:8080"
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow_db
    volumes:
        - ./pipelines/dags:/opt/airflow/dags
        - ./pipelines/scripts:/opt/airflow/scripts
        - ./pipelines/modules:/opt/airflow/modules
        - ./pipelines/data:/opt/airflow/data
        - ./.env:/opt/airflow/.env

    depends_on:
      - postgres
    networks:
      - data_network
    command: >
      bash -c "airflow db migrate && airflow standalone"

  # === DATA TRANSFORMATION ===
  dbt:
    container_name: dbt
    image: ghcr.io/dbt-labs/dbt-postgres:1.9.latest
    volumes:
      - ./dbt/dbt_projects:/usr/app
      - ./dbt:/root/.dbt
    working_dir: /usr/app
    environment:
      DBT_PROFILES_DIR: "/root/.dbt"
    depends_on:
      - postgres
    networks:
      - data_network
    command: run

  # === APIS ===
  # f1-prediction-api:
  #   build:
  #     context: .
  #     dockerfile: apis/f1_prediction_api/Dockerfile
  #   container_name: f1-prediction-api
  #   restart: unless-stopped
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - ./pipelines/models:/app/models:ro
  #   networks:
  #     - data_network
  #   healthcheck:
  #     test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health')"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3
  #     start_period: 10s
  #   depends_on:
  #     - postgres

  f1-position-result-api:
    build:
      context: .
      dockerfile: apis/f1_position_prediction_api/Dockerfile
    container_name: f1-position-result-api
    restart: unless-stopped
    ports:
      - "8001:8001"
    volumes:
      - ./models:/app/models:ro
    networks:
      - data_network
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8001/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local

networks:
  data_network:
    driver: bridge